# Configuration pour EntrepriseManager

types-entreprise:
  Minage:
    blocs-autorisés:
      - STONE
      - COAL_ORE
      - IRON_ORE
    message-erreur:
      - "&4&lSTOP ! Vous avez assez miner pour cette heure !"
      - "&6Pour en obtenir d'avantage, rejoignez une entreprise de type 'Minage'."
      - "&4ou"
      - "&6Attendez l'heure suivante le temps de récupérer de l'énergie."
    limite-non-membre-par-heure: 3
    cout-creation: 10000


  Agriculture:
    blocs-autorisés:
      - WHEAT
      - CARROTS
    message-erreur:
      - "&4&lSTOP ! Vous avez recolter assez pour cette heure !"
      - "&6Pour en obtenir d'avantage, rejoignez une entreprise de type 'Agriculture'."
      - "&4ou"
      - "&6Attendez l'heure suivante le temps de récupérer de l'énergie."
    limite-non-membre-par-heure: 3
    cout-creation: 10000


  Deforestation:
    blocs-autorisés:
      - OAK_LOG
      - SPRUCE_LOG
    message-erreur:
      - "&4&lSTOP ! Vous avez besoin de vous reposer !"
      - "&6Pour en obtenir d'avantage, rejoignez une entreprise de type 'Deforestation'."
      - "&4ou"
      - "&6Attendez l'heure suivante le temps de récupérer de l'énergie."
    limite-non-membre-par-heure: 3
    cout-creation: 10000


finance:
  gain-par-employe: 1000
  max-entreprises-par-gerant: 1
  max-employer-par-entreprise: 1
  max-travail-joueur: 1
  pourcentage-taxes: 15
  heure-paiement: 20

invitation:
  distance-max: 10

siret:
  longueur: 13

rename-cost: 2500
