# Configuration pour les entreprises (Productivité & Spécialisation)
# Mise à jour pour économie RP équilibrée (plafond 100k, améliorations moins chères) : 2025-05-26
# Ajout de l'entreprise Armurerie
# Mise à jour messages d'erreur et ajout items principaux : 2025-06-03 (Gemini)
# Simplification messages de restriction et indication de délai : 2025-06-03 (Gemini)

#--------------------------------------------------------------------------------------------------
# TYPES D'ENTREPRISE
#--------------------------------------------------------------------------------------------------
types-entreprise:

  Minage:
    description: "Extraction de minerais précieux et de matériaux de construction bruts. Items principaux : Diamant, Fer, Or, Charbon."
    action_restrictions:
      BLOCK_BREAK:
        COAL_ORE: {}
        COPPER_ORE: {}
        IRON_ORE: {}
        GOLD_ORE: {}
        LAPIS_ORE: {}
        REDSTONE_ORE: {}
        DIAMOND_ORE: {}
        EMERALD_ORE: {}
        DEEPSLATE_COAL_ORE: {}
        DEEPSLATE_COPPER_ORE: {}
        DEEPSLATE_IRON_ORE: {}
        DEEPSLATE_GOLD_ORE: {}
        DEEPSLATE_LAPIS_ORE: {}
        DEEPSLATE_REDSTONE_ORE: {}
        DEEPSLATE_EMERALD_ORE: {}
        DEEPSLATE_DIAMOND_ORE: {}
        NETHER_QUARTZ_ORE: {}
        ANCIENT_DEBRIS: {}
    activites-payantes:
      BLOCK_BREAK:
        DEEPSLATE: 0.09
        COAL_ORE: 0.70
        COPPER_ORE: 1.20
        IRON_ORE: 2.80
        GOLD_ORE: 4.00
        LAPIS_ORE: 3.80
        REDSTONE_ORE: 1.20
        EMERALD_ORE: 30.00
        DIAMOND_ORE: 60.00
        DEEPSLATE_COAL_ORE: 0.70
        DEEPSLATE_COPPER_ORE: 1.20
        DEEPSLATE_IRON_ORE: 2.80
        DEEPSLATE_GOLD_ORE: 4.00
        DEEPSLATE_LAPIS_ORE: 3.80
        DEEPSLATE_REDSTONE_ORE: 1.20
        DEEPSLATE_EMERALD_ORE: 30.00
        DEEPSLATE_DIAMOND_ORE: 60.00
        NETHER_QUARTZ_ORE: 0.90
        ANCIENT_DEBRIS: 180.00
    message-erreur-restriction: # Simplifié et avec indication de délai
      - "&cSeule une entreprise de &6Minage &cpeut exploiter cette ressource en continu."
      - "&eLimite non-membre : %limite% unités par heure. Vous pourrez réessayer à la prochaine heure."
    limite-non-membre-par-heure: 4
    cout-creation: 12000.0

  Agriculture:
    description: "Culture et récolte de produits végétaux essentiels. Items principaux : Blé, Carottes, Pommes de terre, Verrues du Nether."
    action_restrictions:
      BLOCK_BREAK:
        WHEAT: {}
        CARROTS: {}
        POTATOES: {}
        BEETROOTS: {}
        NETHER_WART: {}
        COCOA_BEANS: {}
        PUMPKIN: {}
        MELON: {}
        SUGAR_CANE: {}
        BAMBOO: {}
        CACTUS: {}
    activites-payantes:
      BLOCK_BREAK:
        WHEAT: 0.45
        CARROTS: 0.35
        POTATOES: 0.35
        BEETROOTS: 0.35
        NETHER_WART: 0.10
        COCOA_BEANS: 0.60
        PUMPKIN: 1.60
        MELON: 1.30
        SUGAR_CANE: 0.30
        BAMBOO: 0.15
        CACTUS: 0.28
    message-erreur-restriction: # Simplifié et avec indication de délai
      - "&cLa culture de masse est réservée aux entreprises &2Agricoles&c."
      - "&eLimite non-membre : %limite% récoltes par heure. Réessayez à la prochaine heure pour plus."
    limite-non-membre-par-heure: 12
    cout-creation: 6000.0
    aide-etat-horaire: 150.0
    services:
      permission-employe: true # Seuls les employés avec la permission ou le gérant peuvent proposer
      liste:
        - nom: "Moisson_Express"
          description: "Récolte complète d'un champ de 50x50 blocs."
          prix: 5000.0
        - nom: "Livraison_Produits_Frais"
          description: "Fourniture d'un stock de 64 blés, 64 carottes et 64 patates."
          prix: 800.0

  Armurerie:
    description: "Forge d'outils, armes et armures robustes. Items principaux : Épées en Diamant, Armures en Fer, Outils en Netherite."
    action_restrictions:
      CRAFT_ITEM:
        DIAMOND_SWORD: {}
        DIAMOND_PICKAXE: {}
        DIAMOND_AXE: {}
        DIAMOND_SHOVEL: {}
        DIAMOND_HOE: {}
        DIAMOND_HELMET: {}
        DIAMOND_CHESTPLATE: {}
        DIAMOND_LEGGINGS: {}
        DIAMOND_BOOTS: {}
        NETHERITE_SWORD: {}
        NETHERITE_PICKAXE: {}
        NETHERITE_AXE: {}
        NETHERITE_SHOVEL: {}
        NETHERITE_HOE: {}
        NETHERITE_HELMET: {}
        NETHERITE_CHESTPLATE: {}
        NETHERITE_LEGGINGS: {}
        NETHERITE_BOOTS: {}
        SHIELD: {}
        BOW: {}
        CROSSBOW: {}
    activites-payantes:
      CRAFT_ITEM:
        IRON_SWORD: 12.0
        IRON_PICKAXE: 18.0
        IRON_AXE: 18.0
        IRON_SHOVEL: 7.0
        IRON_HOE: 12.0
        IRON_HELMET: 28.0
        IRON_CHESTPLATE: 45.0
        IRON_LEGGINGS: 38.0
        IRON_BOOTS: 22.0
        DIAMOND_SWORD: 160.0
        DIAMOND_PICKAXE: 240.0
        DIAMOND_AXE: 240.0
        DIAMOND_SHOVEL: 80.0
        DIAMOND_HOE: 150.0
        DIAMOND_HELMET: 380.0
        DIAMOND_CHESTPLATE: 600.0
        DIAMOND_LEGGINGS: 520.0
        DIAMOND_BOOTS: 300.0
        NETHERITE_SWORD: 1050.0
        NETHERITE_PICKAXE: 1150.0
        NETHERITE_AXE: 1150.0
        NETHERITE_SHOVEL: 900.0
        NETHERITE_HOE: 1020.0
        NETHERITE_HELMET: 1250.0
        NETHERITE_CHESTPLATE: 1500.0
        NETHERITE_LEGGINGS: 1400.0
        NETHERITE_BOOTS: 1180.0
        SHIELD: 10.0
        BOW: 15.0
        CROSSBOW: 30.0
    message-erreur-restriction: # Simplifié et avec indication de délai
      - "&cLa forge de cet équipement requiert une expertise d'&5Armurier&c."
      - "&eLimite non-membre : %limite% fabrications par heure. Réessayez à la prochaine heure."
    limite-non-membre-par-heure: 0
    cout-creation: 18000.0

Bucheronnage:
  description: "Abattage et collecte de divers types de bois. Items principaux : Bûches de Chêne, Sapin, Bois exotiques."
  action_restrictions:
    BLOCK_BREAK:
      OAK_LOG: {}
      SPRUCE_LOG: {}
      BIRCH_LOG: {}
      JUNGLE_LOG: {}
      ACACIA_LOG: {}
      DARK_OAK_LOG: {}
      MANGROVE_LOG: {}
      CHERRY_LOG: {}
      CRIMSON_STEM: {}
      WARPED_STEM: {}
      OAK_WOOD: {}
      SPRUCE_WOOD: {}
      BIRCH_WOOD: {}
      JUNGLE_WOOD: {}
      ACACIA_WOOD: {}
      DARK_OAK_WOOD: {}
      MANGROVE_WOOD: {}
      CHERRY_WOOD: {}
      CRIMSON_HYPHAE: {}
      WARPED_HYPHAE: {}
      STRIPPED_OAK_LOG: {}
      STRIPPED_SPRUCE_LOG: {}
      STRIPPED_BIRCH_LOG: {}
      STRIPPED_JUNGLE_LOG: {}
      STRIPPED_ACACIA_LOG: {}
      STRIPPED_DARK_OAK_LOG: {}
      STRIPPED_MANGROVE_LOG: {}
      STRIPPED_CHERRY_LOG: {}
      STRIPPED_CRIMSON_STEM: {}
      STRIPPED_WARPED_STEM: {}
      STRIPPED_OAK_WOOD: {}
      STRIPPED_SPRUCE_WOOD: {}
      STRIPPED_BIRCH_WOOD: {}
      STRIPPED_JUNGLE_WOOD: {}
      STRIPPED_ACACIA_WOOD: {}
      STRIPPED_DARK_OAK_WOOD: {}
      STRIPPED_MANGROVE_WOOD: {}
      STRIPPED_CHERRY_WOOD: {}
      STRIPPED_CRIMSON_HYPHAE: {}
      STRIPPED_WARPED_HYPHAE: {}
      BAMBOO_BLOCK: {}
      STRIPPED_BAMBOO_BLOCK: {}
  activites-payantes:
    BLOCK_BREAK:
      OAK_LOG: 0.45
      SPRUCE_LOG: 0.50
      BIRCH_LOG: 0.45
      JUNGLE_LOG: 0.60
      ACACIA_LOG: 0.60
      DARK_OAK_LOG: 0.70
      MANGROVE_LOG: 0.75
      CHERRY_LOG: 0.65
      CRIMSON_STEM: 0.90
      WARPED_STEM: 0.90
      OAK_WOOD: 0.45
      SPRUCE_WOOD: 0.50
      BIRCH_WOOD: 0.45
      JUNGLE_WOOD: 0.60
      ACACIA_WOOD: 0.60
      DARK_OAK_WOOD: 0.70
      MANGROVE_WOOD: 0.75
      CHERRY_WOOD: 0.65
      CRIMSON_HYPHAE: 0.90
      WARPED_HYPHAE: 0.90
      STRIPPED_OAK_LOG: 0.45
      STRIPPED_SPRUCE_LOG: 0.50
      STRIPPED_BIRCH_LOG: 0.45
      STRIPPED_JUNGLE_LOG: 0.60
      STRIPPED_ACACIA_LOG: 0.60
      STRIPPED_DARK_OAK_LOG: 0.70
      STRIPPED_MANGROVE_LOG: 0.75
      STRIPPED_CHERRY_LOG: 0.65
      STRIPPED_CRIMSON_STEM: 0.90
      STRIPPED_WARPED_STEM: 0.90
      STRIPPED_OAK_WOOD: 0.45
      STRIPPED_SPRUCE_WOOD: 0.50
      STRIPPED_BIRCH_WOOD: 0.45
      STRIPPED_JUNGLE_WOOD: 0.60
      STRIPPED_ACACIA_WOOD: 0.60
      STRIPPED_DARK_OAK_WOOD: 0.70
      STRIPPED_MANGROVE_WOOD: 0.75
      STRIPPED_CHERRY_WOOD: 0.65
      STRIPPED_CRIMSON_HYPHAE: 0.90
      STRIPPED_WARPED_HYPHAE: 0.90
      BAMBOO_BLOCK: 0.65
      STRIPPED_BAMBOO_BLOCK: 0.65
  message-erreur-restriction: # Simplifié et avec indication de délai
    - "&cL'abattage en quantité de ce bois est réservé aux &6Bûcherons&c."
    - "&eLimite non-membre : %limite% bûches par heure. Réessayez à la prochaine heure."
  limite-non-membre-par-heure: 8
  cout-creation: 7000.0

  Boulangerie:
    description: "Confection de pains, gâteaux et autres délices cuits au four. Items principaux : Pain, Gâteaux, Cookies."
    action_restrictions:
      CRAFT_ITEM:
        BREAD: {}
        CAKE: {}
        COOKIE: {}
        PUMPKIN_PIE: {}
        MUSHROOM_STEW: {}
        RABBIT_STEW: {}
    activites-payantes:
      CRAFT_ITEM:
        BREAD: 1.60
        COOKIE: 0.25
        CAKE: 10.00
        PUMPKIN_PIE: 4.50
        MUSHROOM_STEW: 2.20
        RABBIT_STEW: 7.00
    message-erreur-restriction: # Simplifié et avec indication de délai
      - "&cLa production en grande quantité est réservée aux &eBoulangeries&c."
      - "&eLimite non-membre : %limite% produits par heure. Réessayez à la prochaine heure."
    limite-non-membre-par-heure: 4
    cout-creation: 8000.0

  Construction:
    description: "Pose experte de blocs pour la réalisation de structures variées. Services : Placement de Pierre taillée, Béton, Verre."
    action_restrictions:
      BLOCK_PLACE:
        STONE_BRICKS: {}
        QUARTZ_BLOCK: {}
        GLASS: {}
        TERRACOTTA: {}
        CONCRETE: {}
        BRICKS: {}
        DEEPSLATE_TILES: {}
        POLISHED_BLACKSTONE_BRICKS: {}
    activites-payantes:
      BLOCK_PLACE:
        STONE: 0.01
        DIRT: 0.005
        COBBLESTONE: 0.01
        OAK_PLANKS: 0.02
        SPRUCE_PLANKS: 0.02
        BIRCH_PLANKS: 0.02
        STONE_BRICKS: 0.08
        GLASS: 0.06
        TERRACOTTA: 0.05
        CONCRETE: 0.06
        QUARTZ_BLOCK: 0.15
        BRICKS: 0.07
        SANDSTONE: 0.03
        WOOL: 0.03
        DEEPSLATE_TILES: 0.10
        POLISHED_BLACKSTONE_BRICKS: 0.12
    message-erreur-restriction: # Simplifié et avec indication de délai
      - "&cL'utilisation massive de ce bloc est réservée aux entreprises de &3Construction&c."
      - "&eLimite non-membre : %limite% placements de ce type par heure. Réessayez à la prochaine heure !"
    limite-non-membre-par-heure: 64
    cout-creation: 4000.0

  Boucherie:
    description: "Abattage d'animaux pour la viande et autres produits. Items principaux : Bœuf, Porc, Poulet, Cuir."
    action_restrictions:
      ENTITY_KILL:
        SHEEP: {}
        COW: {}
        PIG: {}
        CHICKEN: {}
        RABBIT: {}
    activites-payantes:
      ENTITY_KILL:
        SHEEP: 2.20
        COW: 3.50
        PIG: 2.80
        CHICKEN: 1.10
        RABBIT: 0.90
    message-erreur-restriction: # Simplifié et avec indication de délai
      - "&cL'abattage en quantité de cet animal est réservé aux &4Boucheries&c."
      - "&eLimite non-membre : %limite% abattages par heure. Réessayez à la prochaine heure."
    limite-non-membre-par-heure: 3
    cout-creation: 7500.0

#--------------------------------------------------------------------------------------------------
# FINANCE ET PARAMÈTRES GLOBAUX
#--------------------------------------------------------------------------------------------------
# ... (Le reste de votre fichier : finance, invitation, siret, rename-cost etc. reste tel quel) ...
finance:
  max-entreprises-par-gerant: 5
  max-travail-joueur: 5

  pourcentage-taxes: 20.0
  charge-salariale-par-employe-horaire: 5.0
  charges-sur-employes-actifs-seulement: false

  allocation-chomage-horaire: 200.0

  max-employer-par-entreprise:
    0: 2
    1: 3
    2: 5
    3: 8
    4: 12

  cout-amelioration-niveau-max-employer:
    1: 2000.0
    2: 6000.0
    3: 15000.0
    4: 35000.0

  max-solde-par-niveau:
    0: 2500.0
    1: 10000.0
    2: 30000.0
    3: 60000.0
    4: 100000.0

  cout-amelioration-niveau-max-solde:
    1: 2000.0
    2: 8000.0
    3: 20000.0
    4: 40000.0

#--------------------------------------------------------------------------------------------------
# INVITATIONS
#--------------------------------------------------------------------------------------------------
invitation:
  distance-max: 10

#--------------------------------------------------------------------------------------------------
# SIRET (Identifiant unique d'entreprise)
#--------------------------------------------------------------------------------------------------
siret:
  longueur: 14

#--------------------------------------------------------------------------------------------------
# DIVERS
#--------------------------------------------------------------------------------------------------
rename-cost: 3000.0


# ----------------------------------------------------- #
#          SUPPRESSION AUTOMATIQUE DES BOUTIQUES          #
# ----------------------------------------------------- #
# Permet d'activer ou de désactiver la suppression automatique des boutiques
# lors de certains événements Towny pour éviter de laisser des shops "fantômes".

shop-deletion-on-events:
  # Événements liés au statut d'un résident dans une ville
  resident-leave-town: true       # Supprime les shops si le propriétaire quitte sa ville.
  resident-kick-from-town: true   # Supprime les shops si le propriétaire est expulsé de sa ville.

  # Événements liés à une parcelle (plot)
  plot-owner-change: true         # Supprime les shops d'une parcelle si son propriétaire change.
  plot-clear: true                # Supprime les shops lors d'une commande /plot clear.
  plot-type-change: true          # Supprime les shops si le type de parcelle n'est plus "Commercial".

  # Événements liés à une ville
  town-unclaim-plot: true         # Supprime les shops si une ville "unclaim" une parcelle.
  town-ruin: true                 # Supprime toutes les boutiques d'une ville si elle tombe en ruines.
