name: RoleplayCity
version: '${project.version}'
main: com.gravityyfh.roleplaycity.RoleplayCity
api-version: 1.20

depend: [Vault, PlaceholderAPI]
softdepend: [QuickShop, CoreProtect, TreeCuter, ProtocolLib, ItemsAdder]
loadbefore: [Essentials, Towny]


commands:
  menu:
    description: Ouvre le menu principal du serveur
    usage: /<command>
    aliases: [m]
  identite:
    description: Affiche votre carte d'identité
    usage: /<command>
    aliases: [id, identity]
  mairie:
    description: Accès aux services municipaux - identité, taxes, rendez-vous, etc.
    usage: /<command> [ville]
    aliases: [townhall, cityhall]
  roleplaycity:
    description: Commandes d'administration du plugin RoleplayCity
    usage: /<command> [reload|version|help]
    aliases: [rpc]
  entreprise:
    description: Système de gestion d'entreprises - Créer et gérer des entreprises
    usage: /<command> [sous-commande] [arguments...]
  ville:
    description: Système de gestion de ville - Interface GUI pour créer, rejoindre et gérer les villes
    usage: /<command> [info|list|gui]
    aliases: [town, city]
  medical:
    description: Système médical - Accepter et gérer les urgences médicales
    usage: /<command> accept <missionId>
    aliases: [medecin, medic]
  mourir:
    description: Abandonner et mourir lorsque vous êtes blessé
    usage: /<command>
    aliases: [die, abandon]
  laposte:
    description: Système de livraison - Envoyer des lettres et des colis aux résidents
    usage: /<command>
    aliases: [poste, mail]
  backpack:
    description: Système de backpacks physiques - Gérer les backpacks
    usage: /<command> [give|reload|info|help]
    aliases: [bp, sac]
  loto:
    description: Ouvre le menu du Loto Horaire
    usage: /<command>
  lotoadmin:
    description: Administration du système de Loto
    usage: /<command> <start|stop|draw|reset|reload>
  le:
    description: Commandes d'administration de LightEconomy (système économique)
    usage: /<command>
    aliases: [lighteconomy, lighteco, leco]
  money:
    description: Commandes économiques pour les joueurs
    usage: /<command>
    aliases: [mon]
  balance:
    description: Affiche le solde d'un joueur
    usage: /<command> [joueur]
    aliases: [bal]
  eco:
    description: Commandes économiques pour la console uniquement
    usage: /<command>
  pay:
    description: Envoyer de l'argent à un autre joueur
    usage: /<command> <joueur> <montant>
  bank:
    description: Système bancaire - Gérer votre compte en banque
    usage: /<command>
  rpc_internal_accept:
    description: Commande interne - Accepter une requête
    usage: /<command> <requestId>
  rpc_internal_refuse:
    description: Commande interne - Refuser une requête
    usage: /<command> <requestId>

permissions:
  roleplaycity.use:
    description: Permet l'utilisation des commandes de base de RoleplayCity
    default: true
  roleplaycity.admin:
    description: Permet l'utilisation des fonctionnalités administratives de RoleplayCity
    default: op
  lotto.use:
    description: Permet de participer au Loto
    default: true
  lotto.admin:
    description: Permet de gérer le Loto (start/stop/draw)
    default: op
  roleplaycity.admin.reload:
    description: Permet de recharger la configuration du plugin avec /roleplaycity reload
    default: op
  roleplaycity.admin.cleandisplay:
    description: Autorise la suppression manuelle d'un item de boutique bloqué
    default: op
  roleplaycity.declare:
    description: Permet de déclarer des entreprises
    default: true
  roleplaycity.manage:
    description: Permet la gestion des entreprises (ajout/suppression d'employés, consultation des infos, etc.)
    default: true
  roleplaycity.town.use:
    description: Permet l'utilisation du système de ville
    default: true
  roleplaycity.town.create:
    description: Permet de créer une ville
    default: true
  roleplaycity.town.admin:
    description: Permet de gérer toutes les villes (administrateurs)
    default: op
  roleplaycity.backpack.give:
    description: Permet de donner des backpacks avec /backpack give
    default: op
  roleplaycity.backpack.reload:
    description: Permet de recharger la configuration des backpacks avec /backpack reload
    default: op
  roleplaycity.backpack.info:
    description: Permet d'afficher les informations d'un backpack avec /backpack info
    default: true

  # Permissions LightEconomy / Banque
  lighteconomy.admin.command.moneyadd:
    description: Permet d'ajouter de l'argent à un joueur
    default: op
  lighteconomy.admin.command.moneyremove:
    description: Permet de retirer de l'argent à un joueur
    default: op
  lighteconomy.admin.command.moneyset:
    description: Permet de définir l'argent d'un joueur
    default: op
  lighteconomy.admin.command.reload:
    description: Permet de recharger la configuration de la banque
    default: op
  lighteconomy.admin.command.debug:
    description: Permet d'activer le mode debug de la banque
    default: op
  lighteconomy.admin.command.balanceother:
    description: Permet de voir le solde d'un autre joueur
    default: op
  lighteconomy.admin.command.moneyaddall:
    description: Permet d'ajouter de l'argent à tous les joueurs
    default: op
  lighteconomy.admin.command.bankadd:
    description: Permet d'ajouter de l'argent au compte bancaire d'un joueur
    default: op
  lighteconomy.admin.command.bankopenother:
    description: Permet d'ouvrir le compte bancaire d'un autre joueur
    default: op
  lighteconomy.admin.command.bankset:
    description: Permet de définir le solde bancaire d'un joueur
    default: op
  lighteconomy.admin.comand.bankremove:
    description: Permet de retirer de l'argent du compte bancaire d'un joueur
    default: op
  lighteconomy.admin.command.banksetlevel:
    description: Permet de définir le niveau bancaire d'un joueur
    default: op
  lighteconomy.admin.command.bankshow:
    description: Permet de voir les infos bancaires d'un joueur
    default: op
  lighteconomy.admin.command.helpadmin:
    description: Permet de voir l'aide admin de la banque
    default: op
  lighteconomy.admin.command.npc.create:
    description: Permet de créer un NPC banquier
    default: op
  lighteconomy.user.command.pay:
    description: Permet de payer un autre joueur
    default: true
  lighteconomy.user.command.moneytop:
    description: Permet de voir le top argent
    default: true
  lighteconomy.user.command.banktop:
    description: Permet de voir le top banque
    default: true
  lighteconomy.user.command.createvoucher:
    description: Permet de créer un billet de banque
    default: true
  lighteconomy.user.command.bank:
    description: Permet d'ouvrir sa banque (via commande)
    default: op
