name: RoleplayCity
version: '${project.version}'
main: com.gravityyfh.roleplaycity.RoleplayCity
api-version: 1.20

softdepend: [QuickShop, CoreProtect, TreeCuter, PlaceholderAPI]


commands:
  roleplaycity:
    description: Commandes d'administration du plugin RoleplayCity
    usage: /<command> [reload|version|help]
    aliases: [rpc]
  entreprise:
    description: Système de gestion d'entreprises - Créer et gérer des entreprises
    usage: /<command> [sous-commande] [arguments...]
  ville:
    description: Système de gestion de ville - Interface GUI pour créer, rejoindre et gérer les villes
    usage: /<command> [info|list|gui]
    aliases: [town, city]
  medical:
    description: Système médical - Accepter et gérer les urgences médicales
    usage: /<command> accept <missionId>
    aliases: [medecin, medic]
  mourir:
    description: Abandonner et mourir lorsque vous êtes blessé
    usage: /<command>
    aliases: [die, abandon]
  laposte:
    description: Système de livraison - Envoyer des lettres et des colis aux résidents
    usage: /<command>
    aliases: [poste, mail]
  backpack:
    description: Système de backpacks physiques - Gérer les backpacks
    usage: /<command> [give|reload|info|help]
    aliases: [bp, sac]
  loto:
    description: Ouvre le menu du Loto Horaire
    usage: /<command>
  lotoadmin:
    description: Administration du système de Loto
    usage: /<command> <start|stop|draw|reset|reload>

permissions:
  roleplaycity.use:
    description: Permet l'utilisation des commandes de base de RoleplayCity
    default: true
  roleplaycity.admin:
    description: Permet l'utilisation des fonctionnalités administratives de RoleplayCity
    default: op
  lotto.use:
    description: Permet de participer au Loto
    default: true
  lotto.admin:
    description: Permet de gérer le Loto (start/stop/draw)
    default: op
  roleplaycity.admin.reload:
    description: Permet de recharger la configuration du plugin avec /roleplaycity reload
    default: op
  roleplaycity.admin.cleandisplay:
    description: Autorise la suppression manuelle d'un item de boutique bloqué
    default: op
  roleplaycity.declare:
    description: Permet de déclarer des entreprises
    default: true
  roleplaycity.manage:
    description: Permet la gestion des entreprises (ajout/suppression d'employés, consultation des infos, etc.)
    default: true
  roleplaycity.town.use:
    description: Permet l'utilisation du système de ville
    default: true
  roleplaycity.town.create:
    description: Permet de créer une ville
    default: true
  roleplaycity.town.admin:
    description: Permet de gérer toutes les villes (administrateurs)
    default: op
  roleplaycity.backpack.give:
    description: Permet de donner des backpacks avec /backpack give
    default: op
  roleplaycity.backpack.reload:
    description: Permet de recharger la configuration des backpacks avec /backpack reload
    default: op
  roleplaycity.backpack.info:
    description: Permet d'afficher les informations d'un backpack avec /backpack info
    default: true
