name: RoleplayCity
version: '${project.version}'
main: com.gravityyfh.roleplaycity.RoleplayCity
api-version: 1.20

softdepend: [QuickShop, CoreProtect, TreeCuter, PlaceholderAPI]


commands:
  roleplaycity:
    description: Commandes d'administration du plugin RoleplayCity
    usage: /<command> [reload|version|help]
    aliases: [rpc]
  entreprise:
    description: Système de gestion d'entreprises - Créer et gérer des entreprises
    usage: /<command> [sous-commande] [arguments...]
  ville:
    description: Système de gestion de ville - Interface GUI pour créer, rejoindre et gérer les villes
    usage: /<command> [info|list|gui]
    aliases: [town, city]
  medical:
    description: Système médical - Accepter et gérer les urgences médicales
    usage: /<command> accept <missionId>
    aliases: [medecin, medic]
  mourir:
    description: Abandonner et mourir lorsque vous êtes blessé
    usage: /<command>
    aliases: [die, abandon]

permissions:
  roleplaycity.use:
    description: Permet l'utilisation des commandes de base de RoleplayCity
    default: true
  roleplaycity.admin:
    description: Permet l'utilisation des fonctionnalités administratives de RoleplayCity
    default: op
  roleplaycity.admin.reload:
    description: Permet de recharger la configuration du plugin avec /roleplaycity reload
    default: op
  roleplaycity.admin.cleandisplay:
    description: Autorise la suppression manuelle d'un item de boutique bloqué
    default: op
  roleplaycity.declare:
    description: Permet de déclarer des entreprises
    default: true
  roleplaycity.manage:
    description: Permet la gestion des entreprises (ajout/suppression d'employés, consultation des infos, etc.)
    default: true
  roleplaycity.town.use:
    description: Permet l'utilisation du système de ville
    default: true
  roleplaycity.town.create:
    description: Permet de créer une ville
    default: true
  roleplaycity.town.admin:
    description: Permet de gérer toutes les villes (administrateurs)
    default: op
