name: RoleplayCity
version: '${project.version}'
main: com.gravityyfh.roleplaycity.RoleplayCity
api-version: 1.20

softdepend: [QuickShop, CoreProtect, TreeCuter, Towny]


commands:
  entreprise:
    description: Commande principale de RoleplayCity, inclut les fonctionnalités pour les joueurs et les administrateurs
    usage: /<command> [sous-commande] [arguments...]
    aliases: [rpc, roleplaycity]

permissions:
  roleplaycity.use:
    description: Permet l'utilisation des commandes de base de RoleplayCity
    default: true
  roleplaycity.admin:
    description: Permet l'utilisation des fonctionnalités administratives de RoleplayCity
    default: op
  roleplaycity.admin.cleandisplay:
    description: Autorise la suppression manuelle d'un item de boutique bloqué
    default: op
  roleplaycity.declare:
    description: Permet de déclarer des entreprises
    default: true
  roleplaycity.manage:
    description: Permet la gestion des entreprises (ajout/suppression d'employés, consultation des infos, etc.)
    default: true
